general.import = [
    "~/.config/alacritty/themes/onedark.toml"
]

[colors]
primary = { background = "#171B24", foreground = "#d8d8d8"}
cursor = { cursor = "#D8D8D8" }

[window]
padding.x = 2
padding.y = 2
decorations = "buttonless"
opacity = 0.99
blur = true
option_as_alt = "both"
startup_mode = "Maximized"

[font]
bold.family = "JetBrainsMono Nerd Font Mono"
bold.style = "Bold"
normal.family = "JetBrainsMono Nerd Font Mono"
normal.style = "Bold"
size = 21.5
