format = """
$directory\
[]()\
[]()\
\n$character"""

right_format = "$git_branch"

[directory]
style = "fg:#80a0ff"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "~/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:##222834"
format = '[[ $symbol $branch ](fg:#769ff0 bg:##222834)]($style)'

