local vim = vim

vim.g.mapleader = " "
vim.g.maplocalleader = " "

vim.opt.termguicolors = true
vim.opt.number = true
vim.opt.relativenumber = true
vim.opt.mouse = "a"
vim.opt.clipboard = "unnamedplus"
vim.opt.undofile = true
vim.opt.undodir = vim.fn.stdpath("state") .. "/undo"
vim.opt.wrap = false
vim.opt.swapfile = false
vim.opt.signcolumn = "yes"
vim.opt.list = false
vim.o.fillchars = "eob: "
vim.opt.inccommand = "split"
vim.opt.cursorline = true
vim.opt.hlsearch = true
vim.opt.breakindent = true
vim.opt.tabstop = 2
vim.opt.shiftwidth = 2
vim.opt.expandtab = true
vim.opt.textwidth = 80
vim.o.winborder = "rounded"
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.timeoutlen = 700
vim.opt.ttimeoutlen = 100
vim.opt.scrolloff = 10
vim.opt.sidescrolloff = 10
vim.o.cmdheight = 0
