require("options")
require("Oil-nvim")
require("mini")
require("harpoon-nvim")
require("blink")
require("keymap")
require("lsp")
require("tree-sitter")
require("colorscheme")
require("lint")
require("snack")
require("autocmds")
-- require("copilot")
require("trouble-nvim")
require("format")
require("extras")
